services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfile-jenkins-local-deploy.yml
    container_name: jenkins-master
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"   # interfaz web Jenkins
      - "50000:50000" # puerto para agentes conectarse
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
