FROM jenkins/jenkins:latest
  
# Cambiar a root para instalar paquetes
USER root
  
# Actualizar repositorios e instalar Maven, Docker CLI, utilidades necesarias
RUN apt-get update && \
apt-get install -y \
maven \
docker.io \
sudo \
&& rm -rf /var/lib/apt/lists/*
  
RUN usermod -aG docker jenkins
RUN usermod -aG sudo jenkins
  
# Volver al usuario Jenkins (mejor para seguridad)
USER jenkins
