spring:
  application:
    name: marketplace-link

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      static-locations: file:uploads/

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    filter: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    doc-expansion: none
  remove-broken-reference-definitions: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    mail:
      enabled: false

frontend:
  url: ${FRONTEND_URL}

moderator:
  default-password: ${MODERATOR_DEFAULT_PASSWORD}

azure:
  storage:
    container-name: ${AZURE_STORAGE_CONTAINER_NAME:imagenes}